---
- name: Setup macOS defaults
  osx_defaults_new:
    array_add: "{{ item.add | default(false) }}"
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  when: item.enable | default(true)
  with_items: "{{ macos_defaults.defaults }}"
  loop_control:
      label: "{{ item.description | default( item.domain + '.' + item.key) }} = {{ item.value }}"
